# SPDX-License-Identifier: GPL-3.0-or-later
"""
---
(c) 2024 David SPORN
---
This is part of prjtabouret -- Documenting the fusemap of the Lattice GAL16V8 PLD and its drop-in replacement MicroChip (Atmel) ATF16V8.

prjtabouret is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your option)
any later version.

prjtabouret is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with prjtabouret.
If not, see <https://www.gnu.org/licenses/>. 
---
"""

import os
import sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from .synthetizer import writeYosysScript


class SynthetizerGal16v8Cli:
    @staticmethod
    def createArgParser() -> ArgumentParser:
        # TODO Rewrite parser as needed
        parser = ArgumentParser(
            prog="python3 -m $$$.pp",
            description="Call yosys to process the given verilog file, in order to get a netlist in json format ready for place and route.",
            epilog="""---
(c) 2024 David SPORN
---
This is part of prjtabouret -- Documenting the fusemap of the Lattice GAL16V8 PLD and its drop-in replacement MicroChip (Atmel) ATF16V8.

prjtabouret is free software: you can redistribute it and/or
modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your option)
any later version.

prjtabouret is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with prjtabouret.
If not, see <https://www.gnu.org/licenses/>. 
---
""",
            formatter_class=RawDescriptionHelpFormatter,
            allow_abbrev=False,
        )

        # Add the arguments
        parser.add_argument(
            "--workdir",
            metavar="<path_workdir>",
            type=str,
            help="the path of the folder into which any required file, including the result, will be generated.",
        )

        # Add the arguments
        # parser.add_argument(
        #    "--lib",
        #    metavar="<path_libfile>",
        #    type=str,
        #    help="the path to the liberty file previously generated by the prjtabouret.gentm command.",
        # )

        # Add the arguments
        parser.add_argument(
            "--topmodule",
            metavar="<module_name>",
            default="top",
            type=str,
            help="the name of the top module.",
        )

        # Source file
        parser.add_argument(
            "source",
            metavar="<source file>",
            type=str,
            help="a single verilog source containing the module to translate into a netlist",
        )

        return parser

    def __init__(self):
        pass

    def run(self):
        try:
            args = SynthetizerGal16v8Cli.createArgParser().parse_args()
            # TODO other things that may throw a value error
        except ValueError as e:
            print(e, file=sys.stderr)
            return 1
        else:
            # check workdir
            if args.workdir:
                if os.path.exists(args.workdir):
                    if not os.path.isdir(args.workdir):
                        print(
                            "ERROR -- specified workdir folder is not a folder",
                            file=sys.stderr,
                        )
                        return 1
                else:
                    try:
                        os.makedirs(args.workdir)
                    except:
                        print("ERROR -- cannot create workdir folder", file=sys.stderr)
                        return 1
            else:
                print(
                    "ERROR -- no workdir folder specified",
                    file=sys.stderr,
                )
                return 1

            # check source
            if args.source:
                if os.path.exists(args.source):
                    if not os.path.isfile(args.source):
                        print(
                            "ERROR -- specified source file is not a file",
                            file=sys.stderr,
                        )
                        return 1
            else:
                print(
                    "ERROR -- no source file specified",
                    file=sys.stderr,
                )
                return 1

            # OK, proceed
            writeYosysScript(args.source, args.workdir, args.topmodule)

            # DONE
            return 0
